NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-ordererorg-example-com.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-ordererorg-example-com.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-ordererorg-example-com.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-ordererorg-example-com.pem
    OrganizationalUnitIdentifier: orderer
